#
# Copyright 2023, Colias Group, LLC
#
# SPDX-License-Identifier: BSD-2-Clause
#

[workspace]

resolver = "2"

members = [
    "hello/pds/hello",
    "banscii/pds/artist",
    "banscii/pds/assistant",
    "banscii/pds/serial-driver",
]
